#!/usr/bin/env ruby
# frozen_string_literal: true

require "pfetch"

help = <<~HELP
  NAME
      pfetch - Fetch some records as json.
  
  
  SYNOPSIS
      pfetch [options] "<query_string>"
  
  
  VERSION
      #{Pfetch::VERSION}
  
  
  
  OPTIONS
      --help                 - Show this message
      --version              - Display the program version
      --sort-by=<sort_field> - Sort returned records by the specified fied
                               <sort_field> can be one of "title", "date" or "relevance"
                               Orders by "date" field if this option is not given.

  EXAMPLE

  pfetch "hello world" --sort
HELP

puts help and exit 0 if ARGV.any? "--help"

puts Pfetch::VERSION.to_s and exit 0 if ARGV.any? "--version"

puts help and exit 128 if ARGV.count == 0

sort_field = ARGV.find { |argv| argv.match(/--sort-by=/) } || "date"
sort_field = sort_field.sub("--sort-by=", "")

query_string = ARGV.find { |argv| !argv.match(/^--/) }
puts help and exit 128 if query_string.nil?

puts Pfetch::Cli.run(query_string: query_string, sort_field: sort_field.to_sym).to_json
exit 0
